--- #This installs asciidoc
- hosts: wp-dev
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Update apt-cache
    apt: update_cache=yes
  - name: Install ASCIIDOC
    apt: pkg=asciidoc state=installed
