--- # This module installs the WordPress CLI
- hosts: wp-dev
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
  - name: Install WordPress CLI 
    get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp owner=ubuntu group=ubuntu mode=0770
  - name: Create .bash directory in home directory
    file: path=/home/ubuntu/.bash state=directory owner=ubuntu group=ubuntu
  - name: Install tab completions
    get_url: url=https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash dest=/home/ubuntu/.bash/wp-completion.bash owner=ubuntu group=ubuntu mode=0770
  - name: Install Plugin
    command: wp plugin install hello-dolly --allow-root chdir=/var/www/html/
