---
- hosts: wp-pb-db
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    wp_mysql_db: MyWP
    wp_mysql_user: wpUser
    wp_mysql_password: wpP4ss
    mysql_root_user: root
    mysql_root_password: Passw0rd
  tasks:
    - name: Create Remote user account
      mysql:
       login_user: {{ mysql_root_user }}
       login_password: {{ mysql_root_password }}
       name: {{ mysql_root_user }}
       password: {{ mysql_root_password }}
       priv=*.*:ALL
       host: "{{ item }}"
       with_items: '{{group.wp-ro-ha}}'
       state=present
